# Generated by Django 5.0.4 on 2026-07-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': [('can_view_all_notes', 'Can view all notes')]},
        ),
    ]
