# Generated by Django 5.0.4 on 2026-07-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_notes', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
