# Generated by Django 5.0.4 on 2026-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_notes', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
